name: havenarc
description: A digital platform for community living, streamlining apartment management and resident engagement.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Authentication
  firebase_core: ^3.12.0   # Update to 3.x.x version
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  firebase_messaging: ^15.2.3  # Update firebase_messaging to match firebase_core
  mobile_scanner: ^3.2.0

  # State Management
  provider: ^6.1.0

  # Networking
  http: ^1.3.0  # Use this version for compatibility

  # Utilities
  shared_preferences: ^2.2.0
  uuid: ^4.5.1
  intl: ^0.20.2

  # UI & Animations
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^18.0.1
  lottie: ^3.3.1
  flutter_animate: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
